spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sc-es-dev
    username: root
    password: anywhere
    platform: mysql
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/