server:
  port: 10001

spring:
  application:
    name: b2c-cart-sidecar

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

sidecar:
  port: 8080
  home-page-uri: http://localhost:${sidecar.port}/
  health-uri: http://localhost:${sidecar.port}/health.json
